# Trust policy to allow pharia-data-api repository to access data-go-packages
# This enables pharia-data-api CI/CD workflows to download this private Go module

# issuer never changes, is the GitHub token issuer
issuer: https://token.actions.githubusercontent.com

# Allow access from any ref (branch, tag, PR) in pharia-data-api repository
subject_pattern: "repo:Aleph-Alpha/pharia-data-api:.*"

# Grant read-only access to repository contents
permissions:
  contents: read
